# Generated by Django 5.1.1 on 2024-11-15 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agris', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SensorData',
            new_name='NPKSensor',
        ),
    ]
