# Generated by Django 5.1.1 on 2024-11-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agris', '0002_rename_sensordata_npksensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbientSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('A_Temp', models.FloatField()),
                ('A_Humid', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SoilSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('S_Temp', models.FloatField()),
                ('S_Humid', models.FloatField()),
            ],
        ),
    ]
